version: "3.8"

services:
  nodejs-api:
    build: .
    ports:
      - "8080:8080"
    container_name: nodejs-api
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db